### ISSUE TITLE
Does this work on 1.18.2 with morphy ?

### ISSUE THREAD

**Issue by datagenn** [libraryaddict/LibsDisguises#655]
Hello,

I just paid, downloaded and installed the latest version and it seems not to be working ?

I bought it so morphy would work without a ton of stacktrace problems with the free version of lib disguises.

Here is the stackstrace I see with the premium version...

[19:20:12] [Server thread/ERROR]: Error occurred while enabling LibsDisguises v10.0.28 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_18_R2/inventory/CraftItemStack
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.getReflectionManager(ReflectionManager.java:773) ~[?:?]
        at me.libraryaddict.disguise.utilities.reflection.ReflectionManager.init(ReflectionManager.java:188) ~[?:?]
        at me.libraryaddict.disguise.LibsDisguises.onEnable(LibsDisguises.java:228) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:611) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:412) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:262) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:993) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot-1.18-R0.1-SNAPSHOT.jar:3339-Spigot-3c40a6c-581df18]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_18_R2.inventory.CraftItemStack
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.18-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 16 more
[19:20:12] [Server thread/INFO]: [Morphy] Enabling Morphy v2.23

Any ideas on this ?

I'm running 1.18.2..

Thanks for your great work you awesome guys!

**Comment by libraryaddict** [comment]
That's a weird issue.

https://www.spigotmc.org/conversations/add?to=libraryaddict

Mind grabbing your latest.log and sending it to me in a private message?
You can also use /ld logs

But given the messages, I'm just going to ask that you're sure that you're running 1.18.2 server.
Because you may be running 1.18 or 1.18.1 instead.

**Comment by datagenn** [comment]
Hi man, thanks for the quick response.

You're right, all this time I thought I was running Spigot 1.18.2, but I wasn't.

I checked the versions.list file inside the Spigot JAR and found this:
e11d32bb35144fa530a27b9d0896b78fbc17f657c0a584a4747935a6f90598ac *spigot-1.18-R0.1-SNAPSHOT.jar

I then downloaded 1.18.2, which says this inside the versions.list file in the JAR:
9b91934d6e79ace5419fe90abf114ddc5196ab04c2bf3fd47f2ce0d881357e89 *spigot-1.18.2-R0.1-SNAPSHOT.jar

After restarting the server with the correct Spigot 1.18.2 JAR file the stacktrace went away.

Things seem to be working much better now but I noticed you can't morph into some mobs, eg: ones that are same size or larger. I can morph into a bee or a baby cow though but not into a baby villager.

Example stacktrace..

`[08:33:45] [Server thread/INFO]: SCRUTICUS issued server command: /morph
[08:33:45] [Server thread/ERROR]: Error executing task on Server
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:461) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1307) ~[?:?]
        at java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:528) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at net.minecraft.server.players.UserCache.c(UserCache.java:281) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.players.UserCache.a(UserCache.java:130) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.world.level.block.entity.TileEntitySkull.b(SourceFile:147) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:140) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1146) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[08:33:59] [Server thread/INFO]: SCRUTICUS issued server command: /morph`

Thanks for the help.
S.

**Comment by libraryaddict** [comment]
https://www.spigotmc.org/wiki/lib-s-disguises-faq/#tall-disguises-self-disguises
